services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mvp
    ports:
      - "27000:27017"
    volumes:
      - ./data/db:/data/db

  fastapi:
    build: ./app
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - MONGO_URL=${MONGO_URL}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
    depends_on:
      - mongo

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: [ "http", "fastapi:8000", "--log", "stdout", "--log-format", "logfmt" ]
    ports:
      - "4040:4040"
    depends_on:
      - fastapi
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
