FROM python:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8000

# Ejecutamos con fastapi run
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]
